### ISSUE TITLE
PR batch 4

### ISSUE THREAD

**Issue by nponeccop** [Torantulino/Auto-GPT#1015]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

The new merging flow is getting traction. So here is another FIFO batch. We don't actively merge the PRs here yet.

### Clean merge 🌈

- #837
- #884
- #980
- #1014
- #1011
- #1016
- #1022
- #1030
- #1031
- #1032
- #1034
- #1038
- #1043
- #1050
- #1053
- #1065
- #1068
- #1071
- #1072
- #1087
- #1095
- #1096
- #1097

### Conflicts or Red CI from Batch 3:

- #367 
- #754
- #837 
- #968

### Labeled

- #289
- #916
- #1042
- #1091
- #1102

### Motivation 🔦

We want to merge older PRs first, so that PR authors are motivated to fix conflicts once their PR gets into a batch. This happens when I, @nponeccop , approve the PR for the first time. I only check that there are no conflicts, CI is green and the PR only fixes one thing and cannot be sensibly split.

Then the PR gets an additional review from @Torantulino , @p-i- or @richbeales . Unlike my simple review, they review the logic extensively, and subsequently merge.

The merged commits are then tested at the end of the day, and merged into the `stable` branch. So people wanting to try Auto-GPT should try `stable`, not `master`. If master gets broken, we fix it by either accepting out-of-band PRs or fix it ourselves.

**Comment by EwoutH** [comment]
Thanks for all this amazing work!

Would you consider using [Squash and merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits) method for merging PRs instead of the "Create a merge commit" method? That will result in a way cleaner, and linear git log, since for each PR not multiple commits (including a merge commit) are included but only a single one.

<img width="290" alt="Screenshot_847" src="https://user-images.githubusercontent.com/15776622/231887785-58942845-87a3-43c3-b12b-772a707a80c4.png">

**Comment by nponeccop** [comment]
@EwoutH Propose in a separate issue, not here

**Comment by EwoutH** [comment]
Done: https://github.com/Torantulino/Auto-GPT/issues/1255

**Comment by nponeccop** [comment]
Today has been a challenging day. We began by merging issues as usual, but ultimately ended up addressing a long-awaited issue with our repository structure: the introduction of the autogpt module.

This change is significant and has impacted issues from Batch 5 and a few from Batch 4 that were still experiencing Git merge conflicts when we decided to move on. We followed the same carry-over procedure as we did with earlier batches.

In addition, we welcomed some new members to our development channels on Discord, including @0xArty , @BillSchumacher , and @merwanehamadi .
